apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: old-app
  namespace: migration-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: old-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
